### ISSUE TITLE
UTF encoding/decoding script

### ISSUE THREAD

**Issue by volga629** [volga629/fusionpbx-dev#10]
We need help create encoding decoding layer for SMS routing

**Comment by ankitvasava98** [comment]
@volga629 

Please find out the lua dna python file into attachments.
with info .txt file for required dependencies and lua command 

[https://app.zenhub.com/files/64152255/9d150c7d-6e78-4ee7-9643-dc5290e3fc52/download](https://app.zenhub.com/files/64152255/9d150c7d-6e78-4ee7-9643-dc5290e3fc52/download)[https://app.zenhub.com/files/64152255/de724697-3103-406f-b3d7-a5c1771afca5/download](https://app.zenhub.com/files/64152255/de724697-3103-406f-b3d7-a5c1771afca5/download)

**Comment by ankitvasava98** [comment]
Hey slava please find out updated lua file with lua function call from opensips as command line argument.


modparam("lua", "luafilename", "/etc/opensips/scripts/cmd.lua")

if(lua_exec("slava_function","encode:UTF16:$rb")) {

you can used slava_function()

[slava-5dec.zip](https://github.com/volga629/fusionpbx-dev/files/3928089/slava-5dec.zip

**Comment by ankitvasava98** [comment]
please find out latest updated lus file with added required functions
[updated-lua.zip](https://github.com/volga629/fusionpbx-dev/files/3928170/updated-lua.zip)
.

**Comment by volga629** [comment]
Updated scripts being push to git hub we continue testing.

https://github.com/volga629/opensips-smpp-lua

**Comment by volga629-1** [comment]
Thank you @ankitvasava98  Script works as expected.
